name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'cloudflare-worker/**' 
      - '.github/workflows/deploy-cf-worker.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker to Cloudflare
    defaults:
      run:
        working-directory: ./cloudflare-worker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install Wrangler
        run: npm install wrangler # Installs wrangler locally

      - name: Upload GitHub Token Secret for Worker Runtime
        # This is the token the worker code (eventAutomation.js) will use as env.GITHUB_TOKEN
        if: ${{ secrets.WORKER_GITHUB_TOKEN != '' }} # Corrected 'if' condition
        run: echo "${{ secrets.WORKER_GITHUB_TOKEN }}" | npx wrangler secret put GITHUB_TOKEN --env production
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Upload Eventbrite Private Token Secret for Worker Runtime
        # This is the token the worker code (eventAutomation.js) will use as env.EVENTBRITE_PRIVATE_TOKEN
        if: ${{ secrets.EVENTBRITE_PRIVATE_TOKEN != '' }} # Corrected 'if' condition
        run: echo "${{ secrets.EVENTBRITE_PRIVATE_TOKEN }}" | npx wrangler secret put EVENTBRITE_PRIVATE_TOKEN --env production
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      # Example for APPS_SCRIPT_SECRET if you decide to add it to GitHub secrets later
      # Ensure you have a corresponding GitHub repository secret (e.g., WORKER_APPS_SCRIPT_SECRET_FROM_GH)
      # - name: Upload Apps Script Secret (Optional)
      #   if: ${{ secrets.WORKER_APPS_SCRIPT_SECRET_FROM_GH != '' }} # Corrected 'if' condition
      #   run: echo "${{ secrets.WORKER_APPS_SCRIPT_SECRET_FROM_GH }}" | npx wrangler secret put APPS_SCRIPT_SECRET --env production
      #   env:
      #     CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      #     CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Deploy Cloudflare Worker
        run: npx wrangler deploy --env production 
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}