name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'cloudflare-worker/**' 
      - '.github/workflows/deploy-cf-worker.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker to Cloudflare
    defaults:
      run:
        working-directory: ./cloudflare-worker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install Wrangler
        run: npm install wrangler # Installs wrangler locally

      - name: Upload GitHub Token Secret for Worker Runtime
        # No step-level 'if' condition here
        run: |
          if [ -n "${{ secrets.WORKER_GITHUB_TOKEN }}" ]; then
            echo "Uploading GITHUB_TOKEN secret..."
            echo "${{ secrets.WORKER_GITHUB_TOKEN }}" | npx wrangler secret put GITHUB_TOKEN
          else
            echo "WORKER_GITHUB_TOKEN secret is not set in GitHub. Skipping upload."
          fi
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Upload Eventbrite Private Token Secret for Worker Runtime
        # No step-level 'if' condition here
        run: |
          if [ -n "${{ secrets.EVENTBRITE_PRIVATE_TOKEN }}" ]; then
            echo "Uploading EVENTBRITE_PRIVATE_TOKEN secret..."
            echo "${{ secrets.EVENTBRITE_PRIVATE_TOKEN }}" | npx wrangler secret put EVENTBRITE_PRIVATE_TOKEN
          else
            echo "EVENTBRITE_PRIVATE_TOKEN secret is not set in GitHub. Skipping upload."
          fi
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      

      - name: Deploy Cloudflare Worker
        run: npx wrangler deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
